<a href="https://colab.research.google.com/github/Varshinie13/Python-Learning-CaseStudies/blob/main/Data_Transformation_in_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Transaformation

In [1]:
import pandas as pd

In [2]:
# Create first DataFrame (Employee details)
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4, 5, 6],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Age': [25, 30, 28, 35, 26, 40],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Marketing', 'Finance'],
    'Salary': [45000, 60000, 52000, 75000, 48000, 82000]
})

# Create second DataFrame (Location details)
df2 = pd.DataFrame({
    'ID': [1, 2, 3, 4, 6, 7],
    'City': ['Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Hyderabad', 'Pune'],
    'State': ['Delhi', 'Maharashtra', 'Karnataka', 'Tamil Nadu', 'Telangana', 'Maharashtra'],
    'Country': ['India', 'India', 'India', 'India', 'India', 'India']
})
print(df1)
print(df2)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   45000
1   2      Bob   30         IT   60000
2   3  Charlie   28    Finance   52000
3   4    David   35         IT   75000
4   5      Eva   26  Marketing   48000
5   6    Frank   40    Finance   82000
   ID       City        State Country
0   1      Delhi        Delhi   India
1   2     Mumbai  Maharashtra   India
2   3  Bangalore    Karnataka   India
3   4    Chennai   Tamil Nadu   India
4   6  Hyderabad    Telangana   India
5   7       Pune  Maharashtra   India

Merge

In [3]:
#INNER JOIN (only matching IDs)
df_inner = pd.merge(
    df1[['ID', 'Name', 'Salary']],
    df2[['ID', 'City']],
    on='ID',
    how='inner'
)
df_inner

   ID     Name  Salary       City
0   1    Alice   45000      Delhi
1   2      Bob   60000     Mumbai
2   3  Charlie   52000  Bangalore
3   4    David   75000    Chennai
4   6    Frank   82000  Hyderabad

In [4]:
#LEFT JOIN (all rows from df1)
df_left = pd.merge(
    df1,
    df2,
    on='ID',
    how='left'
)
df_left

   ID     Name  Age Department  Salary       City        State Country
0   1    Alice   25         HR   45000      Delhi        Delhi   India
1   2      Bob   30         IT   60000     Mumbai  Maharashtra   India
2   3  Charlie   28    Finance   52000  Bangalore    Karnataka   India
3   4    David   35         IT   75000    Chennai   Tamil Nadu   India
4   5      Eva   26  Marketing   48000        NaN          NaN     NaN
5   6    Frank   40    Finance   82000  Hyderabad    Telangana   India

In [5]:
# RIGHT JOIN (all rows from df2)
df_right = pd.merge(
    df1[['ID', 'Name', 'Salary']],
    df2[['ID', 'City']],
    on='ID',
    how='right'
)
df_right

   ID     Name   Salary       City
0   1    Alice  45000.0      Delhi
1   2      Bob  60000.0     Mumbai
2   3  Charlie  52000.0  Bangalore
3   4    David  75000.0    Chennai
4   6    Frank  82000.0  Hyderabad
5   7      NaN      NaN       Pune

In [6]:
# FULL OUTER JOIN (all rows from both tables)
df_outer = pd.merge(
    df1,
    df2,
    on='ID',
    how='outer'
)
df_outer

   ID     Name   Age Department   Salary       City        State Country
0   1    Alice  25.0         HR  45000.0      Delhi        Delhi   India
1   2      Bob  30.0         IT  60000.0     Mumbai  Maharashtra   India
2   3  Charlie  28.0    Finance  52000.0  Bangalore    Karnataka   India
3   4    David  35.0         IT  75000.0    Chennai   Tamil Nadu   India
4   5      Eva  26.0  Marketing  48000.0        NaN          NaN     NaN
5   6    Frank  40.0    Finance  82000.0  Hyderabad    Telangana   India
6   7      NaN   NaN        NaN      NaN       Pune  Maharashtra   India

Joins

In [7]:
# Set ID as index in both
print(df1)
print(df2)

df1 = df1.set_index('ID')
df2 = df2.set_index('ID')

print(df1)
print(df2)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   45000
1   2      Bob   30         IT   60000
2   3  Charlie   28    Finance   52000
3   4    David   35         IT   75000
4   5      Eva   26  Marketing   48000
5   6    Frank   40    Finance   82000
   ID       City        State Country
0   1      Delhi        Delhi   India
1   2     Mumbai  Maharashtra   India
2   3  Bangalore    Karnataka   India
3   4    Chennai   Tamil Nadu   India
4   6  Hyderabad    Telangana   India
5   7       Pune  Maharashtra   India
       Name  Age Department  Salary
ID
1     Alice   25         HR   45000
2       Bob   30         IT   60000
3   Charlie   28    Finance   52000
4     David   35         IT   75000
5       Eva   26  Marketing   48000
6     Frank   40    Finance   82000
         City        State Country
ID
1       Delhi        Delhi   India
2      Mumbai  Maharashtra   India
3   Bangalore    Karnataka   India
4     Chennai   Tamil Nadu   India
6   Hyderabad    Telangana   India
7        Pune  Maharashtra   India

In [8]:
#INNER JOIN (common IDs only)
df_inner = df1.join(df2, how='inner')
print(df_inner)

       Name  Age Department  Salary       City        State Country
ID
1     Alice   25         HR   45000      Delhi        Delhi   India
2       Bob   30         IT   60000     Mumbai  Maharashtra   India
3   Charlie   28    Finance   52000  Bangalore    Karnataka   India
4     David   35         IT   75000    Chennai   Tamil Nadu   India
6     Frank   40    Finance   82000  Hyderabad    Telangana   India

In [9]:
# LEFT JOIN (all rows from df1)
df_left = df1.join(df2, how='left')
print(df_left)

       Name  Age Department  Salary       City        State Country
ID
1     Alice   25         HR   45000      Delhi        Delhi   India
2       Bob   30         IT   60000     Mumbai  Maharashtra   India
3   Charlie   28    Finance   52000  Bangalore    Karnataka   India
4     David   35         IT   75000    Chennai   Tamil Nadu   India
5       Eva   26  Marketing   48000        NaN          NaN     NaN
6     Frank   40    Finance   82000  Hyderabad    Telangana   India

In [10]:
# RIGHT JOIN (all rows from df2)
df_right = df1.join(df2, how='right')
print(df_right)

       Name   Age Department   Salary       City        State Country
ID
1     Alice  25.0         HR  45000.0      Delhi        Delhi   India
2       Bob  30.0         IT  60000.0     Mumbai  Maharashtra   India
3   Charlie  28.0    Finance  52000.0  Bangalore    Karnataka   India
4     David  35.0         IT  75000.0    Chennai   Tamil Nadu   India
6     Frank  40.0    Finance  82000.0  Hyderabad    Telangana   India
7       NaN   NaN        NaN      NaN       Pune  Maharashtra   India

In [11]:
# FULL OUTER JOIN (all rows from both)
df_outer = df1.join(df2, how='outer')
print(df_outer)

       Name   Age Department   Salary       City        State Country
ID
1     Alice  25.0         HR  45000.0      Delhi        Delhi   India
2       Bob  30.0         IT  60000.0     Mumbai  Maharashtra   India
3   Charlie  28.0    Finance  52000.0  Bangalore    Karnataka   India
4     David  35.0         IT  75000.0    Chennai   Tamil Nadu   India
5       Eva  26.0  Marketing  48000.0        NaN          NaN     NaN
6     Frank  40.0    Finance  82000.0  Hyderabad    Telangana   India
7       NaN   NaN        NaN      NaN       Pune  Maharashtra   India

In [12]:
#Reset index for both DataFrames\
df1 = df1.reset_index()
df2 = df2.reset_index()

In [13]:
print(df1)
print(df2)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   45000
1   2      Bob   30         IT   60000
2   3  Charlie   28    Finance   52000
3   4    David   35         IT   75000
4   5      Eva   26  Marketing   48000
5   6    Frank   40    Finance   82000
   ID       City        State Country
0   1      Delhi        Delhi   India
1   2     Mumbai  Maharashtra   India
2   3  Bangalore    Karnataka   India
3   4    Chennai   Tamil Nadu   India
4   6  Hyderabad    Telangana   India
5   7       Pune  Maharashtra   India

Concat

In [14]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'ID': [4, 5, 6],
    'Name': ['David', 'Eva', 'Frank']
})

In [15]:
result = pd.concat([df1, df2],axis=0,ignore_index=True)
print(result)

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David
4   5      Eva
5   6    Frank

In [16]:
result_col = pd.concat([df1, df2], axis=1)
print(result_col)

   ID     Name  ID   Name
0   1    Alice   4  David
1   2      Bob   5    Eva
2   3  Charlie   6  Frank

In [17]:
df3 = pd.DataFrame({
    'ID': [7, 8],
    'City': ['Delhi', 'Mumbai']
})

result_mixed = pd.concat([df1, df3],ignore_index=True)
print(result_mixed)

   ID     Name    City
0   1    Alice     NaN
1   2      Bob     NaN
2   3  Charlie     NaN
3   7      NaN   Delhi
4   8      NaN  Mumbai

Groupby

In [18]:
#sample data
data = {
    'Region': ['East', 'West', 'East', 'North', 'West', 'East'],
    'Sales': [200, 300, 250, 400, 150, 350],
    'Profit': [20, 30, 25, 40, 15, 35]
}

df =pd.DataFrame(data)

In [19]:
# 1. Summarize Total Sales by Region
# Find total sales generated in each region

print(df.groupby("Region")["Sales"].sum())

Region
East     800
North    400
West     450
Name: Sales, dtype: int64

In [20]:
# 2. Find Average Profit by Region
# Calculate average profit for each region

print(df.groupby("Region")["Profit"].mean())

Region
East     26.666667
North    40.000000
West     22.500000
Name: Profit, dtype: float64

In [21]:
# 3. Count Number of Records by Region
# Count how many sales records exist in each region

print(df.groupby("Region")["Sales"].count())
region_count =df.groupby("Region")["Sales"].count()
region_count

Region
East     3
North    1
West     2
Name: Sales, dtype: int64

Region
East     3
North    1
West     2
Name: Sales, dtype: int64

In [22]:
# 4. Find Maximum Sales by Region
# Identify highest an lowest sales and profit value in each region

min_max = df.groupby("Region")[["Sales","Profit"]].agg(["min","max"])
min_max

       Sales      Profit
         min  max    min max
Region
East     200  350     20  35
North    400  400     40  40
West     150  300     15  30

Multiple Aggregations :.agg() if you want to apply one or more aggregation in column

In [23]:
# 5. Perform Multiple Aggregations
# Generate multiple summary statistics together
df.groupby("Region")[["Sales", "Profit"]].agg(["sum", "mean", "max", "min"])

       Sales                       Profit
         sum        mean  max  min    sum       mean max min
Region
East     800  266.666667  350  200     80  26.666667  35  20
North    400  400.000000  400  400     40  40.000000  40  40
West     450  225.000000  300  150     45  22.500000  30  15

Cross Tab in Pandas

In [24]:
# Sample Data
data = {
    'Region': ['East', 'West', 'East', 'North', 'West', 'East'],
    'Category': ['Electronics', 'Furniture', 'Electronics',
                 'Furniture', 'Clothing', 'Clothing'],
    'Sales': [200, 300, 250, 400, 150, 350],
    'Profit': [20, 30, 25, 40, 15, 35]
}

df = pd.DataFrame(data)

In [25]:
# Objective:Analyze frequency distribution between Region and Category
cross_tab = pd.crosstab(df["Region"],df["Category"])
cross_tab

Category  Clothing  Electronics  Furniture
Region
East             1            2          0
North            0            0          1
West             1            0          1

In [26]:
cross_tab_multi_sum = pd.crosstab(df["Region"],df["Category"],
                              values=df["Sales"],aggfunc=["sum"]
)
cross_tab_multi_sum

              sum
Category Clothing Electronics Furniture
Region
East        350.0       450.0       NaN
North         NaN         NaN     400.0
West        150.0         NaN     300.0

In [27]:
# CROSS TAB WITH MULTIPLE AGGREGATIONS
# Objective: Calculate sum and average sales
cross_tab_multi = pd.crosstab(df["Region"],df["Category"],
                              values=df["Sales"],aggfunc=["sum", "mean"]
)

cross_tab_multi

              sum                           mean
Category Clothing Electronics Furniture Clothing Electronics Furniture
Region
East        350.0       450.0       NaN    350.0       225.0       NaN
North         NaN         NaN     400.0      NaN         NaN     400.0
West        150.0         NaN     300.0    150.0         NaN     300.0