<a href="https://colab.research.google.com/github/Varshinie13/Python-Learning-CaseStudies/blob/main/Data_ingestion_and_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [4]:
import datetime as dt
import numpy as np

In [3]:
# Upload File from Your Local System
#  Import files module
from google.colab import files

# Upload file from local system
uploaded = files.upload()

#data frame conversion
df = pd.read_csv("Employee_data.csv")
df

Saving Employee_data.csv to Employee_data (1).csv

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
0,1000,hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0,NaN
1,1001,ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0,remove_me
2,1002,frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1,remove_me
3,1003,david,NaN,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN,remove_me
4,1004,mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1,remove_me
...,...,...,...,...,...,...,...,...,...,...,...
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1,NaN
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0,remove_me
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1,remove_me
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0,NaN
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No,remove_me

In [5]:
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
0,1000,hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0,NaN
1,1001,ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0,remove_me
2,1002,frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1,remove_me
3,1003,david,NaN,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN,remove_me
4,1004,mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1,remove_me
...,...,...,...,...,...,...,...,...,...,...,...
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1,NaN
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0,remove_me
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1,remove_me
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0,NaN
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No,remove_me

In [6]:
#Initial Inspection

#returns 1st 5 -  Rows

df.head()

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
0,1000,hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0,NaN
1,1001,ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0,remove_me
2,1002,frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1,remove_me
3,1003,david,NaN,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN,remove_me
4,1004,mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1,remove_me

In [7]:
#Returns 1st 25 rows

df.head(25)

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
0,1000,hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0,NaN
1,1001,ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0,remove_me
2,1002,frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1,remove_me
3,1003,david,NaN,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN,remove_me
4,1004,mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1,remove_me
5,1005,BOB,90.0,HR,Intern*,02/20/20,NaN,poor,11-11-2025 19:00,0,NaN
6,1006,paula,32.0,FINANCE,Intern*,13-09-2023,"45,500",NaN,NaN,No,remove_me
7,1007,hannah,32.0,HR,@Manager,"Oct 13, 2018",60000,excellent,NaN,NaN,remove_me
8,1008,GRACE,NaN,finance,Intern*,"Aug 27, 2022","65,000",NaN,31-10-2025 11:00,1,NaN
9,1009,OSCAR,26.0,finance,!Clerk,"Sep 11, 2023",NaN,good,NaN,1,remove_me
10,1010,laura,28.0,it,@Manager,"Jan 11, 2018",70k,excellent,31-10-2025 19:00,1,remove_me
11,1011,JULIA,NaN,IT,Sr@Analyst,05-07-2021,70k,good,02-11-2025 21:00,0,remove_me
12,1012,HANNAH,28.0,IT,#Analyst,03-Jul-24,NaN,NaN,12-11-2025 07:00,1,remove_me
13,1013,HANNAH,28.0,HR,!Clerk,01-Sep-19,70k,average,09-11-2025 01:00,NaN,remove_me
14,1014,alice,90.0,sales,#Analyst,16-Jan-24,55000,NaN,05-11-2025 04:00,0,NaN
15,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0,remove_me
16,1016,MIKE,30.0,HR,!Clerk,03-10-2024,60000,average,05-11-2025 06:00,0,remove_me
17,1017,KEVIN,90.0,MARKETING,@Manager,26-Mar-22,NaN,NaN,NaN,0,remove_me
18,1018,ivan,90.0,it,#Analyst,11-08-2021,"45,500",excellent,04-11-2025 19:00,Yes,remove_me
19,1019,CHARLIE,28.0,HR,#Analyst,09-05-2020,70k,NaN,06-11-2025 19:00,NaN,remove_me
20,1020,ivan,35.0,hr,#Analyst,18-04-2022,55000,good,02-11-2025 15:00,1,NaN
21,1021,LAURA,32.0,FINANCE,Intern*,10-08-2022,55000,poor,04-11-2025 09:00,0,remove_me
22,1022,QUINN,26.0,sales,@Manager,27-Jul-21,"65,000",good,NaN,1,NaN
23,1023,MIKE,90.0,FINANCE,#Analyst,11-Apr-22,60000,poor,04-11-2025 17:00,1,NaN
24,1024,RITA,30.0,sales,@Manager,16-Sep-19,50000,good,10-11-2025 23:00,0,remove_me

Data Inspection

In [8]:
#returns last 5 rows

df.tail()

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1,NaN
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0,remove_me
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1,remove_me
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0,NaN
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No,remove_me

In [9]:
#returns last 10 rows
df.tail(10)

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
195,1195,NINA,26.0,marketing,Sr@Analyst,07-07-2020,60000,poor,07-11-2025 09:00,Yes,NaN
196,1196,PAULA,26.0,finanace,#Analyst,12-05-2021,"45,500",NaN,08-11-2025 16:00,0,remove_me
197,1197,alice,30.0,finance,Data-Scientist,14-02-2022,"65,000",good,11-11-2025 22:00,0,remove_me
198,1198,MIKE,32.0,IT,!Clerk,02/15/21,"45,500",average,NaN,1,NaN
199,1199,kevin,28.0,it,$Developer$,15-Jul-20,40000,average,03-11-2025 16:00,Yes,NaN
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1,NaN
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0,remove_me
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1,remove_me
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0,NaN
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No,remove_me

In [10]:
#Returns - how many rows and column in dataset

df.shape

(205, 11)

In [11]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Department', 'Position', 'Joining_Date',
       'Salary', 'Feedback', 'Last_Login_Time', 'Has_Car', 'Useless_Col'],
      dtype='object')

In [12]:
#returns information about the data

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Employee_ID      205 non-null    int64
 1   Name             205 non-null    object
 2   Age              174 non-null    float64
 3   Department       205 non-null    object
 4   Position         205 non-null    object
 5   Joining_Date     205 non-null    object
 6   Salary           188 non-null    object
 7   Feedback         142 non-null    object
 8   Last_Login_Time  150 non-null    object
 9   Has_Car          186 non-null    object
 10  Useless_Col      112 non-null    object
dtypes: float64(1), int64(1), object(9)
memory usage: 17.7+ KB

In [15]:
#returns the datatypes of the columns

df.dtypes

Employee_ID          int64
Name                object
Age                float64
Department          object
Position            object
Joining_Date        object
Salary              object
Feedback            object
Last_Login_Time     object
Has_Car             object
Useless_Col         object
dtype: object

In [16]:
#returns and describe the numerical columns in dataset

df.describe()

       Employee_ID         Age
count   205.000000  174.000000
mean   1099.151220   37.528736
std      57.855902   21.307460
min    1000.000000   24.000000
25%    1049.000000   26.000000
50%    1099.000000   30.000000
75%    1149.000000   35.000000
max    1199.000000   90.000000

In [17]:
#Checks the null values and count how many null values in each columns

df.isnull().sum()

Employee_ID         0
Name                0
Age                31
Department          0
Position            0
Joining_Date        0
Salary             17
Feedback           63
Last_Login_Time    55
Has_Car            19
Useless_Col        93
dtype: int64

In [20]:
#returns the sum of duplicate values in dataset

df.duplicated().sum()

np.int64(5)

In [21]:
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
0,1000,hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0,NaN
1,1001,ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0,remove_me
2,1002,frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1,remove_me
3,1003,david,NaN,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN,remove_me
4,1004,mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1,remove_me
...,...,...,...,...,...,...,...,...,...,...,...
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1,NaN
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0,remove_me
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1,remove_me
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0,NaN
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No,remove_me

Data Cleaning and Transformation

Removing unwanted columns and rows

In [22]:
#if you want make a copy

df_safe = df.copy

In [23]:
#drop the unwanted columns

df.drop('Useless_Col',axis = 1, inplace = True)  #inplace makes the changes in original columns

In [24]:
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0
1,1001,ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0
2,1002,frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1
3,1003,david,NaN,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN
4,1004,mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No

In [25]:
#drop a row (drop 204)

df.drop(204,axis = 0, inplace = True)
df.tail(10)

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
194,1194,IVAN,NaN,FINANCE,!Clerk,26-Sep-19,55000,good,09-11-2025 03:00,No
195,1195,NINA,26.0,marketing,Sr@Analyst,07-07-2020,60000,poor,07-11-2025 09:00,Yes
196,1196,PAULA,26.0,finanace,#Analyst,12-05-2021,"45,500",NaN,08-11-2025 16:00,0
197,1197,alice,30.0,finance,Data-Scientist,14-02-2022,"65,000",good,11-11-2025 22:00,0
198,1198,MIKE,32.0,IT,!Clerk,02/15/21,"45,500",average,NaN,1
199,1199,kevin,28.0,it,$Developer$,15-Jul-20,40000,average,03-11-2025 16:00,Yes
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0

In [ ]:
#Filter the data

#Drop rows based on condition  no inplace it work on only method
df = df[df['Department'] == 'IT']

Duplication Removal

In [28]:
#Display Duplicate Rows
df[df.duplicated()]

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0

In [29]:
#Display All Occurrences of Duplicates
df[df.duplicated(keep = False)]

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
15,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0
30,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1
95,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1
158,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0

In [31]:
# Remove duplicates from the dataset
df.drop_duplicates(inplace = True)

In [32]:
#check - Is there any duplicates occur in the dataset
df.duplicated().sum()

np.int64(0)

In [ ]:
#drop a row (by index)
df.drop(0, axis=0, inplace=True)
df.drop([0, 2], axis=0, inplace=True)

Handlling null values(missing data)

In [34]:
#returns null values in the columns

df.isnull().sum()

Employee_ID         0
Name                0
Age                31
Department          0
Position            0
Joining_Date        0
Salary             16
Feedback           60
Last_Login_Time    55
Has_Car            19
dtype: int64

In [36]:
#name column cleaning
df['Name'] = df['Name'].str.title()   #First letter caplitalise in the 'Name' column
df.head()

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0
1,1001,Ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0
2,1002,Frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1
3,1003,David,NaN,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN
4,1004,Mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1

In [37]:
#Age columns - use median when there is outliers

df['Age'].fillna(df['Age'].median(),inplace = True)

#df['Age'].fillna(20,inplace = True )               # fill 20 in Null places

#df['Age'].fillna(df['Age'].mean(),inplace = True)     #Age columns - you can use mean

#df['Age'].fillna(df['Age'].mode().[0],inplace = True)     #Age columns - you can use mode #if 2 modes - take 0 index value

/tmp/ipykernel_2108/1336306304.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(),inplace = True)

In [43]:
df.isnull().sum()

Employee_ID         0
Name                0
Age                 0
Department          0
Position            0
Joining_Date        0
Salary             16
Feedback           60
Last_Login_Time    55
Has_Car            19
dtype: int64

In [44]:
#check the values in column

df['Department'].unique()

array(['finance', 'it', 'IT', 'finanace', 'HR', 'FINANCE', 'sales',
       'MARKETING', 'hr', 'FINANACE', 'marketing', 'SALES'], dtype=object)

In [45]:
#chance the department to upper case

df['Department'] = df['Department'].str.upper()

In [46]:
#returns unique values of department column
df['Department'].unique()

array(['FINANCE', 'IT', 'FINANACE', 'HR', 'SALES', 'MARKETING'],
      dtype=object)

In [48]:
# chanege the Values
df['Department'].replace({'FINANACE':'Finance',
                          'FINANCE': 'Finance',
                          'SALES': 'Sales',
                          'MARKETING': 'Marketing'},inplace = True
                          )

/tmp/ipykernel_2108/4073139858.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Department'].replace({'FINANACE':'Finance',

In [49]:
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,30.0,Finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0
1,1001,Ivan,30.0,IT,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0
2,1002,Frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1
3,1003,David,30.0,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN
4,1004,Mike,28.0,Finance,$Developer$,16-Aug-19,60000,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...
195,1195,Nina,26.0,Marketing,Sr@Analyst,07-07-2020,60000,poor,07-11-2025 09:00,Yes
196,1196,Paula,26.0,Finance,#Analyst,12-05-2021,"45,500",NaN,08-11-2025 16:00,0
197,1197,Alice,30.0,Finance,Data-Scientist,14-02-2022,"65,000",good,11-11-2025 22:00,0
198,1198,Mike,32.0,IT,!Clerk,02/15/21,"45,500",average,NaN,1
199,1199,Kevin,28.0,IT,$Developer$,15-Jul-20,40000,average,03-11-2025 16:00,Yes

In [47]:
#returns positions unique values
df['Position'].unique()

array(['$Developer$', 'Sr@Analyst', 'Intern*', 'Data-Scientist',
       '@Manager', '!Clerk', '#Analyst'], dtype=object)

In [51]:
#Remove the unknown character from position column

df['Position']=df['Position'].str.replace(r'[^a-zA-Z ]',' ', regex=True)
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,30.0,Finance,Developer,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0
1,1001,Ivan,30.0,IT,Sr Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0
2,1002,Frank,32.0,IT,Intern,19-04-2023,70k,good,NaN,1
3,1003,David,30.0,IT,Data Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN
4,1004,Mike,28.0,Finance,Developer,16-Aug-19,60000,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...
195,1195,Nina,26.0,Marketing,Sr Analyst,07-07-2020,60000,poor,07-11-2025 09:00,Yes
196,1196,Paula,26.0,Finance,Analyst,12-05-2021,"45,500",NaN,08-11-2025 16:00,0
197,1197,Alice,30.0,Finance,Data Scientist,14-02-2022,"65,000",good,11-11-2025 22:00,0
198,1198,Mike,32.0,IT,Clerk,02/15/21,"45,500",average,NaN,1
199,1199,Kevin,28.0,IT,Developer,15-Jul-20,40000,average,03-11-2025 16:00,Yes

In [52]:
#returns unique values in the columns
df['Salary'].unique()

array(['70k', '45,500', '40000', '60000', nan, '65,000', '55000', '50000'],
      dtype=object)

In [53]:
#Clean the salary

df['Salary']=df['Salary'].str.replace('k','000').str.replace(',','')

In [56]:
#case conversion
df['Salary']=df['Salary'].astype(float)

In [57]:
df['Salary'].describe()

count      184.000000
mean     54266.304348
std      10110.982799
min      40000.000000
25%      45500.000000
50%      55000.000000
75%      61250.000000
max      70000.000000
Name: Salary, dtype: float64

In [58]:
# Hierarchical imputation
# Level 1: Department + Position mean
dept_pos_mean = df.groupby(['Department','Position'])['Salary'].transform('median')

# # Level 2: Department mean
dept_mean = df.groupby('Department')['Salary'].transform('mean')

# # Level 3: Overall mean
overall_mean = df['Salary'].mean()

# Hierarchical imputation
df['Salary'] = (df['Salary']
    .fillna(dept_pos_mean)
    .fillna(dept_mean)
    .fillna(overall_mean)
)

In [59]:
df.isnull().sum()

Employee_ID         0
Name                0
Age                 0
Department          0
Position            0
Joining_Date        0
Salary              0
Feedback           60
Last_Login_Time    55
Has_Car            19
dtype: int64

In [60]:
df['Feedback'].unique()

array(['poor', 'excellent', 'good', nan, 'average', '?'], dtype=object)

In [61]:
#Returns the values count of the columns for each category

df['Feedback'].value_counts()

Feedback
poor         31
good         29
average      29
?            26
excellent    25
Name: count, dtype: int64

In [62]:
#Replace the values
df['Feedback'] = df['Feedback'].str.replace('?','unknown').str.title()

In [63]:
#Replace the values using Fillna

df['Feedback'] = df['Feedback'].fillna('unknown')

In [64]:
#Returns the values count of the columns for each category
df['Feedback'].value_counts()

Feedback
unknown      60
Poor         31
Average      29
Good         29
Unknown      26
Excellent    25
Name: count, dtype: int64

In [65]:
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,30.0,Finance,Developer,"Sep 16, 2023",70000.0,Poor,11-11-2025 22:00,0
1,1001,Ivan,30.0,IT,Sr Analyst,29-Aug-22,45500.0,Excellent,07-11-2025 05:00,0
2,1002,Frank,32.0,IT,Intern,19-04-2023,70000.0,Good,NaN,1
3,1003,David,30.0,IT,Data Scientist,02/14/23,40000.0,Poor,31-10-2025 19:00,NaN
4,1004,Mike,28.0,Finance,Developer,16-Aug-19,60000.0,unknown,NaN,1
...,...,...,...,...,...,...,...,...,...,...
195,1195,Nina,26.0,Marketing,Sr Analyst,07-07-2020,60000.0,Poor,07-11-2025 09:00,Yes
196,1196,Paula,26.0,Finance,Analyst,12-05-2021,45500.0,unknown,08-11-2025 16:00,0
197,1197,Alice,30.0,Finance,Data Scientist,14-02-2022,65000.0,Good,11-11-2025 22:00,0
198,1198,Mike,32.0,IT,Clerk,02/15/21,45500.0,Average,NaN,1
199,1199,Kevin,28.0,IT,Developer,15-Jul-20,40000.0,Average,03-11-2025 16:00,Yes

In [66]:
#Check the unique values of the column

df['Has_Car'].unique()

array(['0', '1', nan, 'No', 'Yes'], dtype=object)

In [70]:
df['Has_Car'].replace({'0':'No','1':'Yes'},inplace = True)  #Replace the values in the column

In [71]:
df['Has_Car']=df['Has_Car'].fillna('Unknown') #fill the null values as unknown

In [73]:
df.head(25)

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,30.0,Finance,Developer,"Sep 16, 2023",70000.0,Poor,11-11-2025 22:00,No
1,1001,Ivan,30.0,IT,Sr Analyst,29-Aug-22,45500.0,Excellent,07-11-2025 05:00,No
2,1002,Frank,32.0,IT,Intern,19-04-2023,70000.0,Good,NaN,Yes
3,1003,David,30.0,IT,Data Scientist,02/14/23,40000.0,Poor,31-10-2025 19:00,Unknown
4,1004,Mike,28.0,Finance,Developer,16-Aug-19,60000.0,unknown,NaN,Yes
5,1005,Bob,90.0,HR,Intern,02/20/20,55000.0,Poor,11-11-2025 19:00,No
6,1006,Paula,32.0,Finance,Intern,13-09-2023,45500.0,unknown,NaN,No
7,1007,Hannah,32.0,HR,Manager,"Oct 13, 2018",60000.0,Excellent,NaN,Unknown
8,1008,Grace,30.0,Finance,Intern,"Aug 27, 2022",65000.0,unknown,31-10-2025 11:00,Yes
9,1009,Oscar,26.0,Finance,Clerk,"Sep 11, 2023",52500.0,Good,NaN,Yes
10,1010,Laura,28.0,IT,Manager,"Jan 11, 2018",70000.0,Excellent,31-10-2025 19:00,Yes
11,1011,Julia,30.0,IT,Sr Analyst,05-07-2021,70000.0,Good,02-11-2025 21:00,No
12,1012,Hannah,28.0,IT,Analyst,03-Jul-24,55000.0,unknown,12-11-2025 07:00,Yes
13,1013,Hannah,28.0,HR,Clerk,01-Sep-19,70000.0,Average,09-11-2025 01:00,Unknown
14,1014,Alice,90.0,Sales,Analyst,16-Jan-24,55000.0,unknown,05-11-2025 04:00,No
15,1015,Grace,32.0,Finance,Developer,"Nov 14, 2021",60000.0,Average,07-11-2025 20:00,No
16,1016,Mike,30.0,HR,Clerk,03-10-2024,60000.0,Average,05-11-2025 06:00,No
17,1017,Kevin,90.0,Marketing,Manager,26-Mar-22,55000.0,unknown,NaN,No
18,1018,Ivan,90.0,IT,Analyst,11-08-2021,45500.0,Excellent,04-11-2025 19:00,Yes
19,1019,Charlie,28.0,HR,Analyst,09-05-2020,70000.0,unknown,06-11-2025 19:00,Unknown
20,1020,Ivan,35.0,HR,Analyst,18-04-2022,55000.0,Good,02-11-2025 15:00,Yes
21,1021,Laura,32.0,Finance,Intern,10-08-2022,55000.0,Poor,04-11-2025 09:00,No
22,1022,Quinn,26.0,Sales,Manager,27-Jul-21,65000.0,Good,NaN,Yes
23,1023,Mike,90.0,Finance,Analyst,11-Apr-22,60000.0,Poor,04-11-2025 17:00,Yes
24,1024,Rita,30.0,Sales,Manager,16-Sep-19,50000.0,Good,10-11-2025 23:00,No

In [74]:
#column name renaming
df.rename(columns={"Department": "Department_Name"}, inplace=True)

In [75]:
df

,Employee_ID,Name,Age,Department_Name,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,30.0,Finance,Developer,"Sep 16, 2023",70000.0,Poor,11-11-2025 22:00,No
1,1001,Ivan,30.0,IT,Sr Analyst,29-Aug-22,45500.0,Excellent,07-11-2025 05:00,No
2,1002,Frank,32.0,IT,Intern,19-04-2023,70000.0,Good,NaN,Yes
3,1003,David,30.0,IT,Data Scientist,02/14/23,40000.0,Poor,31-10-2025 19:00,Unknown
4,1004,Mike,28.0,Finance,Developer,16-Aug-19,60000.0,unknown,NaN,Yes
...,...,...,...,...,...,...,...,...,...,...
195,1195,Nina,26.0,Marketing,Sr Analyst,07-07-2020,60000.0,Poor,07-11-2025 09:00,Yes
196,1196,Paula,26.0,Finance,Analyst,12-05-2021,45500.0,unknown,08-11-2025 16:00,No
197,1197,Alice,30.0,Finance,Data Scientist,14-02-2022,65000.0,Good,11-11-2025 22:00,No
198,1198,Mike,32.0,IT,Clerk,02/15/21,45500.0,Average,NaN,Yes
199,1199,Kevin,28.0,IT,Developer,15-Jul-20,40000.0,Average,03-11-2025 16:00,Yes

In [76]:
# Convert Joining_Date to datetime
df['Joining_Date'] = pd.to_datetime(df['Joining_Date'],format="mixed",errors='coerce',dayfirst=True)

In [77]:
# Convert Joining_Date to specific format datetime

df['Joining_Date'] = pd.to_datetime(
    df['Joining_Date'],format="%d-%m-%Y",errors='coerce')

In [79]:
df.head()

,Employee_ID,Name,Age,Department_Name,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,30.0,Finance,Developer,2023-09-16,70000.0,Poor,11-11-2025 22:00,No
1,1001,Ivan,30.0,IT,Sr Analyst,2022-08-29,45500.0,Excellent,07-11-2025 05:00,No
2,1002,Frank,32.0,IT,Intern,2023-04-19,70000.0,Good,NaN,Yes
3,1003,David,30.0,IT,Data Scientist,2023-02-14,40000.0,Poor,31-10-2025 19:00,Unknown
4,1004,Mike,28.0,Finance,Developer,2019-08-16,60000.0,unknown,NaN,Yes

In [80]:
df.isnull().sum()

Employee_ID         0
Name                0
Age                 0
Department_Name     0
Position            0
Joining_Date        0
Salary              0
Feedback            0
Last_Login_Time    55
Has_Car             0
dtype: int64

In [81]:
df['Last_Login_Time'] = pd.to_datetime(df['Last_Login_Time'],format="mixed",errors='coerce',dayfirst=True)

In [86]:
df['Last_Login_Time'] = pd.to_datetime(
    df['Last_Login_Time'],format="%d-%m-%Y %H:%M",errors='coerce')

In [87]:
df.head()

,Employee_ID,Name,Age,Department_Name,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,30.0,Finance,Developer,2023-09-16,70000.0,Poor,2025-11-11 22:00:00,No
1,1001,Ivan,30.0,IT,Sr Analyst,2022-08-29,45500.0,Excellent,2025-11-07 05:00:00,No
2,1002,Frank,32.0,IT,Intern,2023-04-19,70000.0,Good,NaT,Yes
3,1003,David,30.0,IT,Data Scientist,2023-02-14,40000.0,Poor,2025-10-31 19:00:00,Unknown
4,1004,Mike,28.0,Finance,Developer,2019-08-16,60000.0,unknown,NaT,Yes

In [90]:
#Given values to fill the null values in the column

df['Last_Login_Time'] = df['Last_Login_Time'].fillna(pd.to_datetime('2025-01-01 00:00:00'))
df.isnull().sum()

Employee_ID        0
Name               0
Age                0
Department_Name    0
Position           0
Joining_Date       0
Salary             0
Feedback           0
Last_Login_Time    0
Has_Car            0
dtype: int64

In [94]:
df.dtypes

Employee_ID                 int64
Name                       object
Age                       float64
Department_Name            object
Position                   object
Joining_Date       datetime64[ns]
Salary                    float64
Feedback                   object
Last_Login_Time    datetime64[ns]
Has_Car                    object
dtype: object