<a href="https://colab.research.google.com/github/Varshinie13/Python-Learning-CaseStudies/blob/main/Pandas_practice_session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#installing pandas
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
#Importing pandas
import pandas as pd

In [3]:
# Series 1D array
s = pd.Series([100, 200, 300, 400])
print(s)
print(type(s))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
# 2D array

data = {'Name':["Arvind","Vinoth","Fathima","Jeni","Karthiga"],
        'Age': [25,30,26,28,29],
        'City':["Bangalore","Chennai","Mumbai","Chennai","Hydrabad"]}
print(data)

{'Name': ['Arvind', 'Vinoth', 'Fathima', 'Jeni', 'Karthiga'], 'Age': [25, 30, 26, 28, 29], 'City': ['Bangalore', 'Chennai', 'Mumbai', 'Chennai', 'Hydrabad']}

In [6]:
df = pd.DataFrame(data)
df

       Name  Age       City
0    Arvind   25  Bangalore
1    Vinoth   30    Chennai
2   Fathima   26     Mumbai
3      Jeni   28    Chennai
4  Karthiga   29   Hydrabad

In [7]:
# Creating Dictionary
data = {
    'ID': [101, 102, 103, 104, 105, 106],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Age': [24, 30, 28, 35, 22, 40],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Berlin', 'Sydney'],
    'Salary': [50000, 60000, 55000, 70000, 48000, 75000],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'Marketing', 'Finance']
}

print(data)

{'ID': [101, 102, 103, 104, 105, 106], 'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'], 'Age': [24, 30, 28, 35, 22, 40], 'City': ['New York', 'London', 'Paris', 'Tokyo', 'Berlin', 'Sydney'], 'Salary': [50000, 60000, 55000, 70000, 48000, 75000], 'Department': ['HR', 'IT', 'Finance', 'IT', 'Marketing', 'Finance']}

In [9]:
df = pd.DataFrame(data)
df

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
3  104    David   35     Tokyo   70000         IT
4  105      Eva   22    Berlin   48000  Marketing
5  106    Frank   40    Sydney   75000    Finance

In [10]:
#Accessing Columns (single element)

df['Age']

0    24
1    30
2    28
3    35
4    22
5    40
Name: Age, dtype: int64

In [13]:
#Accessing Columns (multiple element)

df[["Name","Age","City"]]

      Name  Age      City
0    Alice   24  New York
1      Bob   30    London
2  Charlie   28     Paris
3    David   35     Tokyo
4      Eva   22    Berlin
5    Frank   40    Sydney

In [14]:
#Accessing Rows (multiple rows)

df[0:3]

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance

In [18]:
#using loc to access elements(label based indexing)

print(df.loc[2,'Name'])
print(df.loc[1,'Name'])

Charlie
Bob

In [21]:
#using loc for slicing

df.loc[:2:2]

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
2  103  Charlie   28     Paris   55000    Finance

In [23]:
#Accessing multiple element (using loc)

print(df.loc[2:3, ["Name", "Age","Salary"]])

      Name  Age  Salary
2  Charlie   28   55000
3    David   35   70000

In [24]:
#Accessing element using iloc (Single row)

df.iloc[0]

ID                 101
Name             Alice
Age                 24
City          New York
Salary           50000
Department          HR
Name: 0, dtype: object

In [26]:
#Accessing single element using iloc(rows and columns)
df.iloc[0,3]

'New York'

In [27]:
#difference between loc and iloc

print(df.loc[0,"Name"])
print(df.iloc[0,1])

Alice
Alice

In [30]:
#loc - includes the end lable
#iloc - excludes the end label
print("-------loc - OutPut------")
print(df.loc[0:2])
print("-------iloc - OutPut------")
print(df.iloc[0:2])

-------loc - OutPut------
    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
-------iloc - OutPut------
    ID   Name  Age      City  Salary Department
0  101  Alice   24  New York   50000         HR
1  102    Bob   30    London   60000         IT

In [33]:
#Filtering Data

df[df["Age"] <= 30]

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
4  105      Eva   22    Berlin   48000  Marketing

In [35]:
df[df["Salary"] >= 60000 ]

    ID   Name  Age    City  Salary Department
1  102    Bob   30  London   60000         IT
3  104  David   35   Tokyo   70000         IT
5  106  Frank   40  Sydney   75000    Finance

In [36]:
df_dept = df[df["Department"] == "IT"]
print(df_dept)

    ID   Name  Age    City  Salary Department
1  102    Bob   30  London   60000         IT
3  104  David   35   Tokyo   70000         IT

In [39]:
#Filter using logical operators

print("-------------And operator output-------")

df[(df["Age"] >= 30 ) & (df["Salary"] >= 60000)]

-------------And operator output-------

    ID   Name  Age    City  Salary Department
1  102    Bob   30  London   60000         IT
3  104  David   35   Tokyo   70000         IT
5  106  Frank   40  Sydney   75000    Finance

In [43]:
print("-------------OR operator output-------")

df[(df["Age"] >= 35 ) | (df["Salary"] >= 50000)]

-------------OR operator output-------

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
3  104    David   35     Tokyo   70000         IT
5  106    Frank   40    Sydney   75000    Finance

In [44]:
#sorting Data based on  Age

df.sort_values("Age")

    ID     Name  Age      City  Salary Department
4  105      Eva   22    Berlin   48000  Marketing
0  101    Alice   24  New York   50000         HR
2  103  Charlie   28     Paris   55000    Finance
1  102      Bob   30    London   60000         IT
3  104    David   35     Tokyo   70000         IT
5  106    Frank   40    Sydney   75000    Finance

In [45]:
#sort using salary

df.sort_values("Salary")

    ID     Name  Age      City  Salary Department
4  105      Eva   22    Berlin   48000  Marketing
0  101    Alice   24  New York   50000         HR
2  103  Charlie   28     Paris   55000    Finance
1  102      Bob   30    London   60000         IT
3  104    David   35     Tokyo   70000         IT
5  106    Frank   40    Sydney   75000    Finance

In [46]:
#adding column

df.loc[6] = [107,"George",37,"Berlin",78000,"Marketing"]
df

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
3  104    David   35     Tokyo   70000         IT
4  105      Eva   22    Berlin   48000  Marketing
5  106    Frank   40    Sydney   75000    Finance
6  107   George   37    Berlin   78000  Marketing

In [47]:
#adding column (len())

df.loc[len(df)] = [108,"Genelia",33,"Auckland",80000,"IT"]
df

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   50000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
3  104    David   35     Tokyo   70000         IT
4  105      Eva   22    Berlin   48000  Marketing
5  106    Frank   40    Sydney   75000    Finance
6  107   George   37    Berlin   78000  Marketing
7  108  Genelia   33  Auckland   80000         IT

In [48]:
#updating value

df.loc[0,'Salary'] = 55000
df

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   55000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
3  104    David   35     Tokyo   70000         IT
4  105      Eva   22    Berlin   48000  Marketing
5  106    Frank   40    Sydney   75000    Finance
6  107   George   37    Berlin   78000  Marketing
7  108  Genelia   33  Auckland   80000         IT

In [50]:
#update value(using loc) - do not know index number

df.loc[df['Name'] == "Genelia",'Age'] = 35
df

    ID     Name  Age      City  Salary Department
0  101    Alice   24  New York   55000         HR
1  102      Bob   30    London   60000         IT
2  103  Charlie   28     Paris   55000    Finance
3  104    David   35     Tokyo   70000         IT
4  105      Eva   22    Berlin   48000  Marketing
5  106    Frank   40    Sydney   75000    Finance
6  107   George   37    Berlin   78000  Marketing
7  108  Genelia   35  Auckland   80000         IT

In [51]:
#deleting Columns

df_new = df.drop("Department",axis = 1)
df_new

    ID     Name  Age      City  Salary
0  101    Alice   24  New York   55000
1  102      Bob   30    London   60000
2  103  Charlie   28     Paris   55000
3  104    David   35     Tokyo   70000
4  105      Eva   22    Berlin   48000
5  106    Frank   40    Sydney   75000
6  107   George   37    Berlin   78000
7  108  Genelia   35  Auckland   80000